join: "&a%player%&b присоединился к игре"
leave: "&a%player%&b покинул игру"
chat-distance: 10
player-format: "[%parties_color_code%%parties_party%&r] %player%: %message%"

local-chat-format: "[&6Local&r]"
global-chat-format: "[&bGlobal&r]"